# Dockerfile.ui
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
COPY requirement.txt .
RUN pip install --no-cache-dir -r requirement.txt

# Copy app files
COPY . .

# Expose port for Streamlit
EXPOSE 8501

CMD ["streamlit", "run", "ui/ui_streamlit_fastapi.py", "--server.port=8501", "--server.address=0.0.0.0"]
